:linkcss:
:stylesdir: https://darshandsoni.com/asciidoctor-skins/css
:stylesheet: monospace.css

= Nombre del caso de uso
:title-page: use-case
:revdate: 2022-05-21
:revnumber: 1.0
:revremark: Plantilla para casos de uso
:version-label!:
:lang: es
:toc:
:toc-title: Tabla de contenidos
:icons: font

<<<

== Descripción
== Actores
== Precondiciones
== Flujo
== Flujo/s alternativo/s
== Post-condiciones
== Excepciones
== Comentarios

<<<

== Ayuda
// tag::ayuda[]
Distribución del documento y como cumplimentarlo
====
.Cabecera
----
= Nombre del caso de uso <1>
:revdate: <2>
:revnumber: <3>
:revremark: <4>
----
<1> Nombre del caso de uso
<2> Fecha de última revisión
<3> Número de versión
<4> Breve resumen

.Secciones del caso de uso
----
== Descripción <1>
== Actores <2>
== Precondiciones <3>
== Flujo <4>
== Flujo/s alternativo/s <5>
== Post-condiciones <6>
== Excepciones <7>
== Comentarios <8>
----
<1> Corresponde a un texto breve donde se refleje el propósito del caso de uso
<2> Los nombres de los actores deben ser un sustantivo singular que represente el rol que juegan en el sistema
<3> Se indican las condiciones necesarias para que se pueda realizar el caso de uso
<4> Enumerar la secuencia normal de interacciones del caso de uso que se deben cumplir para lograr su objetivo o el mejor escenario posible
<5> Enumerar los posibles caminos alternativos
<6> Todos los posibles estados en los que puede finalizar el caso de uso
<7> Se indica el comportamiento del sistema en caso de que se produzca
alguna situación inesperada en el sistema
<8> Información complementaria al caso de uso

====
// end::ayuda[]




